backend: fix bluetooth discovery
If there is no bluetooth interface, discovery fails and USB discovery
is ignored.

Fix the following error:

  File /cups/backend/phomemo.py, line 14, in scan_bluetooth
    manager = dbus.Interface(bus.get_object('org.bluez', '/'),
  ...

dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply:
Did not receive a reply.
Possible causes include: the remote application did not send a reply,
the message bus security policy blocked the reply, the reply timeout expired,
or the network connection was broken.

Signed-off-by: Laurent Vivier <laurent@vivier.eu>