backend: fix USB discovery
Move usb import from scan_usb() to main part to fix the following error:

    File /cups/backend/phomemo.py, line 54, in __call__
      intf = usb.util.find_descriptor(
  NameError: name 'usb' is not defined

Fixes: 556d84d35199 ("Make usb import optional")
Signed-off-by: Laurent Vivier <laurent@vivier.eu>